// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.eventer.app.entity;

public final class Msg {
  private Msg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ContainerOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string MID = 1;
    /**
     * <code>optional string MID = 1;</code>
     */
    boolean hasMID();
    /**
     * <code>optional string MID = 1;</code>
     */
    java.lang.String getMID();
    /**
     * <code>optional string MID = 1;</code>
     */
    com.google.protobuf.ByteString
        getMIDBytes();

    // required string SID = 2;
    /**
     * <code>required string SID = 2;</code>
     */
    boolean hasSID();
    /**
     * <code>required string SID = 2;</code>
     */
    java.lang.String getSID();
    /**
     * <code>required string SID = 2;</code>
     */
    com.google.protobuf.ByteString
        getSIDBytes();

    // required string RID = 3;
    /**
     * <code>required string RID = 3;</code>
     */
    boolean hasRID();
    /**
     * <code>required string RID = 3;</code>
     */
    java.lang.String getRID();
    /**
     * <code>required string RID = 3;</code>
     */
    com.google.protobuf.ByteString
        getRIDBytes();

    // required uint32 TYPE = 4;
    /**
     * <code>required uint32 TYPE = 4;</code>
     */
    boolean hasTYPE();
    /**
     * <code>required uint32 TYPE = 4;</code>
     */
    int getTYPE();

    // required int64 STIME = 5;
    /**
     * <code>required int64 STIME = 5;</code>
     */
    boolean hasSTIME();
    /**
     * <code>required int64 STIME = 5;</code>
     */
    long getSTIME();

    // required string BODY = 6;
    /**
     * <code>required string BODY = 6;</code>
     */
    boolean hasBODY();
    /**
     * <code>required string BODY = 6;</code>
     */
    java.lang.String getBODY();
    /**
     * <code>required string BODY = 6;</code>
     */
    com.google.protobuf.ByteString
        getBODYBytes();
  }
  /**
   * Protobuf type {@code Container}
   */
  public static final class Container extends
      com.google.protobuf.GeneratedMessage
      implements ContainerOrBuilder {
    // Use Container.newBuilder() to construct.
    private Container(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Container(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Container defaultInstance;
    public static Container getDefaultInstance() {
      return defaultInstance;
    }

    public Container getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Container(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sID_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              rID_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              tYPE_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sTIME_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              bODY_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Msg.internal_static_message_Container_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Msg.internal_static_message_Container_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Msg.Container.class, Msg.Container.Builder.class);
    }

    public static com.google.protobuf.Parser<Container> PARSER =
        new com.google.protobuf.AbstractParser<Container>() {
      public Container parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Container(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Container> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string MID = 1;
    public static final int MID_FIELD_NUMBER = 1;
    private java.lang.Object mID_;
    /**
     * <code>optional string MID = 1;</code>
     */
    public boolean hasMID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string MID = 1;</code>
     */
    public java.lang.String getMID() {
      java.lang.Object ref = mID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string MID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMIDBytes() {
      java.lang.Object ref = mID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string SID = 2;
    public static final int SID_FIELD_NUMBER = 2;
    private java.lang.Object sID_;
    /**
     * <code>required string SID = 2;</code>
     */
    public boolean hasSID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string SID = 2;</code>
     */
    public java.lang.String getSID() {
      java.lang.Object ref = sID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string SID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSIDBytes() {
      java.lang.Object ref = sID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string RID = 3;
    public static final int RID_FIELD_NUMBER = 3;
    private java.lang.Object rID_;
    /**
     * <code>required string RID = 3;</code>
     */
    public boolean hasRID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string RID = 3;</code>
     */
    public java.lang.String getRID() {
      java.lang.Object ref = rID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string RID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRIDBytes() {
      java.lang.Object ref = rID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 TYPE = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private int tYPE_;
    /**
     * <code>required uint32 TYPE = 4;</code>
     */
    public boolean hasTYPE() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 TYPE = 4;</code>
     */
    public int getTYPE() {
      return tYPE_;
    }

    // required int64 STIME = 5;
    public static final int STIME_FIELD_NUMBER = 5;
    private long sTIME_;
    /**
     * <code>required int64 STIME = 5;</code>
     */
    public boolean hasSTIME() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 STIME = 5;</code>
     */
    public long getSTIME() {
      return sTIME_;
    }

    // required string BODY = 6;
    public static final int BODY_FIELD_NUMBER = 6;
    private java.lang.Object bODY_;
    /**
     * <code>required string BODY = 6;</code>
     */
    public boolean hasBODY() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string BODY = 6;</code>
     */
    public java.lang.String getBODY() {
      java.lang.Object ref = bODY_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bODY_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string BODY = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBODYBytes() {
      java.lang.Object ref = bODY_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bODY_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      mID_ = "";
      sID_ = "";
      rID_ = "";
      tYPE_ = 0;
      sTIME_ = 0L;
      bODY_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTYPE()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSTIME()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBODY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getRIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, tYPE_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, sTIME_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getBODYBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, tYPE_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sTIME_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getBODYBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Msg.Container parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Container parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Container parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Msg.Container parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Msg.Container parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Container parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Msg.Container parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Msg.Container parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Msg.Container parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Msg.Container parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Msg.Container prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Container}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Msg.ContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Msg.internal_static_message_Container_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Msg.internal_static_message_Container_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Msg.Container.class, Msg.Container.Builder.class);
      }

      // Construct using Msg.Container.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        mID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        tYPE_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sTIME_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        bODY_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Msg.internal_static_message_Container_descriptor;
      }

      public Msg.Container getDefaultInstanceForType() {
        return Msg.Container.getDefaultInstance();
      }

      public Msg.Container build() {
        Msg.Container result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Msg.Container buildPartial() {
        Msg.Container result = new Msg.Container(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mID_ = mID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sID_ = sID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rID_ = rID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.tYPE_ = tYPE_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sTIME_ = sTIME_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.bODY_ = bODY_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Msg.Container) {
          return mergeFrom((Msg.Container)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Msg.Container other) {
        if (other == Msg.Container.getDefaultInstance()) return this;
        if (other.hasMID()) {
          bitField0_ |= 0x00000001;
          mID_ = other.mID_;
          onChanged();
        }
        if (other.hasSID()) {
          bitField0_ |= 0x00000002;
          sID_ = other.sID_;
          onChanged();
        }
        if (other.hasRID()) {
          bitField0_ |= 0x00000004;
          rID_ = other.rID_;
          onChanged();
        }
        if (other.hasTYPE()) {
          setTYPE(other.getTYPE());
        }
        if (other.hasSTIME()) {
          setSTIME(other.getSTIME());
        }
        if (other.hasBODY()) {
          bitField0_ |= 0x00000020;
          bODY_ = other.bODY_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSID()) {
          
          return false;
        }
        if (!hasRID()) {
          
          return false;
        }
        if (!hasTYPE()) {
          
          return false;
        }
        if (!hasSTIME()) {
          
          return false;
        }
        if (!hasBODY()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Msg.Container parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Msg.Container) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string MID = 1;
      private java.lang.Object mID_ = "";
      /**
       * <code>optional string MID = 1;</code>
       */
      public boolean hasMID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string MID = 1;</code>
       */
      public java.lang.String getMID() {
        java.lang.Object ref = mID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          mID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string MID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMIDBytes() {
        java.lang.Object ref = mID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string MID = 1;</code>
       */
      public Builder setMID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string MID = 1;</code>
       */
      public Builder clearMID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mID_ = getDefaultInstance().getMID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string MID = 1;</code>
       */
      public Builder setMIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mID_ = value;
        onChanged();
        return this;
      }

      // required string SID = 2;
      private java.lang.Object sID_ = "";
      /**
       * <code>required string SID = 2;</code>
       */
      public boolean hasSID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string SID = 2;</code>
       */
      public java.lang.String getSID() {
        java.lang.Object ref = sID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string SID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSIDBytes() {
        java.lang.Object ref = sID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string SID = 2;</code>
       */
      public Builder setSID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string SID = 2;</code>
       */
      public Builder clearSID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sID_ = getDefaultInstance().getSID();
        onChanged();
        return this;
      }
      /**
       * <code>required string SID = 2;</code>
       */
      public Builder setSIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sID_ = value;
        onChanged();
        return this;
      }

      // required string RID = 3;
      private java.lang.Object rID_ = "";
      /**
       * <code>required string RID = 3;</code>
       */
      public boolean hasRID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string RID = 3;</code>
       */
      public java.lang.String getRID() {
        java.lang.Object ref = rID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string RID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRIDBytes() {
        java.lang.Object ref = rID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string RID = 3;</code>
       */
      public Builder setRID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string RID = 3;</code>
       */
      public Builder clearRID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rID_ = getDefaultInstance().getRID();
        onChanged();
        return this;
      }
      /**
       * <code>required string RID = 3;</code>
       */
      public Builder setRIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        rID_ = value;
        onChanged();
        return this;
      }

      // required uint32 TYPE = 4;
      private int tYPE_ ;
      /**
       * <code>required uint32 TYPE = 4;</code>
       */
      public boolean hasTYPE() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 TYPE = 4;</code>
       */
      public int getTYPE() {
        return tYPE_;
      }
      /**
       * <code>required uint32 TYPE = 4;</code>
       */
      public Builder setTYPE(int value) {
        bitField0_ |= 0x00000008;
        tYPE_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 TYPE = 4;</code>
       */
      public Builder clearTYPE() {
        bitField0_ = (bitField0_ & ~0x00000008);
        tYPE_ = 0;
        onChanged();
        return this;
      }

      // required int64 STIME = 5;
      private long sTIME_ ;
      /**
       * <code>required int64 STIME = 5;</code>
       */
      public boolean hasSTIME() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 STIME = 5;</code>
       */
      public long getSTIME() {
        return sTIME_;
      }
      /**
       * <code>required int64 STIME = 5;</code>
       */
      public Builder setSTIME(long value) {
        bitField0_ |= 0x00000010;
        sTIME_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 STIME = 5;</code>
       */
      public Builder clearSTIME() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sTIME_ = 0L;
        onChanged();
        return this;
      }

      // required string BODY = 6;
      private java.lang.Object bODY_ = "";
      /**
       * <code>required string BODY = 6;</code>
       */
      public boolean hasBODY() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string BODY = 6;</code>
       */
      public java.lang.String getBODY() {
        java.lang.Object ref = bODY_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bODY_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string BODY = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBODYBytes() {
        java.lang.Object ref = bODY_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bODY_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string BODY = 6;</code>
       */
      public Builder setBODY(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bODY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string BODY = 6;</code>
       */
      public Builder clearBODY() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bODY_ = getDefaultInstance().getBODY();
        onChanged();
        return this;
      }
      /**
       * <code>required string BODY = 6;</code>
       */
      public Builder setBODYBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        bODY_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Container)
    }

    static {
      defaultInstance = new Container(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Container)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_message_Container_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_message_Container_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\007message\"]\n\tContainer\022\013\n\003MID" +
      "\030\001 \001(\t\022\013\n\003SID\030\002 \002(\t\022\013\n\003RID\030\003 \002(\t\022\014\n\004TYPE" +
      "\030\004 \002(\r\022\r\n\005STIME\030\005 \002(\003\022\014\n\004BODY\030\006 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_message_Container_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_message_Container_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_message_Container_descriptor,
              new java.lang.String[] { "MID", "SID", "RID", "TYPE", "STIME", "BODY", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
